services:
  kafka:
    container_name: notif-leasing-kafka-test
    hostname: notif-leasing-kafka-test
    ports:
      - 9092:9092
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 2@notif-leasing-kafka-test:29093
      KAFKA_LISTENERS: BROKER://notif-leasing-kafka-test:29092,CONTROLLER://notif-leasing-kafka-test:29093,HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: BROKER://notif-leasing-kafka-test:29092,HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  redis:
    container_name: notif-leasing-redis-test
    ports:
      - 6379:6379
  postgres:
    container_name: notif-leasing-postgres-test
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fadhil
      POSTGRES_PASSWORD: 8phtnsf7
      POSTGRES_db: notif-leasing-db-test
volumes:
  redisdata:
  pgdata:
